In [1]:
import pandas as pd 
import numpy as np 
import seaborn as sns 
import matplotlib.pyplot as plt 
import tensorflow 
from tensorflow import keras

In [2]:
doc="""Why did the computer go to the doctor because it had a virus.
I told my laptop a joke but it did not laugh it just crashed.
Why do programmers prefer dark mode because light attracts bugs.
My computer beat me at chess but it was no match for me at kickboxing.
Why did the developer go broke because he used up all his cache.
I asked the computer for a joke and it said error humor not found.
Why was the math book sad because it had too many problems.
I tried to catch fog yesterday but I mist.
Why did the scarecrow win an award because he was outstanding in his field.
I told my phone to sleep but it kept waking up with notifications.
Why did the AI cross the road to optimize the other side.
I asked my keyboard for advice but it said press any key to continue.
Why did the computer get cold because it left its windows open.
My WiFi and I have a strong connection but sometimes it drops suddenly.
Why do Java developers wear glasses because they do not see sharp.
Why did the robot go on vacation because it needed to recharge.
I asked my computer to sing but it only produced byte music.
Why did the programmer quit his job because he did not get arrays.
I told my computer a secret but it leaked the data.
Why did the server break up with the client because it lost connection.
I tried to organize a hide and seek game with programmers but good luck hiding from recursion.
Why was the computer tired because it had too many tabs open.
My computer loves coffee because it runs on java.
Why do programmers hate nature because it has too many bugs.
I tried to explain coding to my friend but he said it did not compute.
Why did the database administrator leave the party because there were too many joins.
My laptop and I argue sometimes but we always reconnect.
Why did the AI go to school to improve its learning rate.
I asked the computer to tell a joke but it returned null.
Why was the smartphone nervous because it lost its signal.
I opened too many tabs and now my browser needs therapy.
Why did the programmer stay calm because he knew how to handle exceptions.
My computer told me a joke but it was only binary humor.
Why did the internet break up with the router because there was no connection.
I tried to debug my life but there were too many errors.
Why did the programmer bring a ladder to work because he wanted to reach the cloud.
My code works perfectly until someone else looks at it.
Why did the robot become a musician because it loved heavy metal.
I told my computer a funny joke but it needed more processing time.
Why do programmers drink coffee because code does not compile without it.
I asked the AI for advice but it said please upgrade to premium intelligence.
Why was the computer late because it had too many processes running.
My laptop battery and motivation have something in common they both run out quickly.
Why did the programmer go outside because the documentation said it was user friendly.
I tried to fix my code but I only added more bugs.
Why did the computer blush because it saw the internet history.
My computer laughs in binary whenever I tell a joke.
Why did the programmer use glasses because he could not see the bug.
I asked the computer if it was tired but it said it just needed to reboot.
Why did the robot fail school because it kept copying answers.
My computer thinks every problem can be solved with restart.
Why did the programmer stay up all night because he was debugging dreams.
I asked the AI to cook but it only produced byte sized meals.
Why did the computer go to therapy because it had memory issues.
My laptop thinks sleep mode means nap time forever.
Why did the developer carry a pencil in case he needed to draw a diagram.
I told my computer to relax but it kept running programs.
Why was the internet slow because everyone was downloading jokes.
My computer likes jokes that have good syntax.
Why did the robot laugh because it understood the algorithm.
I tried to tell my computer a joke but it flagged it as spam.
Why did the programmer cross the road because the code told him to execute.
My laptop refuses to work on Mondays just like me.
Why did the computer get promoted because it processed everything quickly.
I asked the AI to tell a story but it started training itself.
Why did the programmer become a chef because he loved cooking scripts.
My computer does not like jokes without logic.
Why did the server feel lonely because no one pinged it.
I tried to impress my computer but it said insufficient permissions.
Why did the robot join the gym to improve its processing power.
My computer laughs only when the code compiles successfully.
Why did the programmer smile because his code finally worked.
I asked my computer for a break but it said system busy.
Why did the AI read books to increase its knowledge base.
My laptop loves jokes that have good algorithms.
Why did the programmer sleep peacefully because there were no bugs.
I tried to teach my computer humor but it returned syntax error.
Why did the computer become a teacher because it loved explaining logic.
My computer believes every bug is just an unexpected feature.
Why did the programmer bring snacks because debugging takes energy.
I asked the AI to relax but it started optimizing itself.
Why did the computer laugh because it understood the code.
My laptop enjoys jokes that are well structured.
Why did the robot write poetry because it loved neural networks.
I tried to outsmart my computer but it already predicted my move.
Why did the programmer celebrate because the model finally converged.
My computer says life is just a loop with conditions.
Why did the AI smile because the dataset was clean.
I asked my computer to tell a joke but it needed more data.
Why did the developer relax because the deployment was successful.
My computer enjoys jokes with good training data.
Why did the robot learn math to improve its calculations.
I asked the AI for humor but it generated a dataset instead.
Why did the programmer laugh because the bug fixed itself.
My laptop thinks every problem is solvable with an algorithm.
Why did the computer meditate to clear its cache.
I asked my computer to predict the future but it needed more epochs.
Why did the programmer relax because the model accuracy improved.
My computer says debugging is like solving puzzles.
Why did the AI tell jokes because it learned from the dataset."""

In [3]:
from keras_preprocessing.text import Tokenizer 
tokenizer=Tokenizer()

In [4]:
doc=doc.split('\n')

In [5]:
tokenizer.fit_on_texts(doc)

In [6]:
tokenizer.word_counts

OrderedDict([('why', 51),
             ('did', 45),
             ('the', 79),
             ('computer', 36),
             ('go', 6),
             ('to', 38),
             ('doctor', 1),
             ('because', 45),
             ('it', 54),
             ('had', 5),
             ('a', 22),
             ('virus', 1),
             ('i', 33),
             ('told', 7),
             ('my', 40),
             ('laptop', 8),
             ('joke', 8),
             ('but', 30),
             ('not', 8),
             ('laugh', 4),
             ('just', 5),
             ('crashed', 1),
             ('do', 5),
             ('programmers', 4),
             ('prefer', 1),
             ('dark', 1),
             ('mode', 2),
             ('light', 1),
             ('attracts', 1),
             ('bugs', 4),
             ('beat', 1),
             ('me', 4),
             ('at', 3),
             ('chess', 1),
             ('was', 15),
             ('no', 4),
             ('match', 1),
             ('for', 6)

In [7]:
tokenizer.word_index #each value get a unique no 

{'the': 1,
 'it': 2,
 'why': 3,
 'did': 4,
 'because': 5,
 'my': 6,
 'to': 7,
 'computer': 8,
 'i': 9,
 'but': 10,
 'a': 11,
 'was': 12,
 'programmer': 13,
 'asked': 14,
 'he': 15,
 'ai': 16,
 'tried': 17,
 'laptop': 18,
 'joke': 19,
 'not': 20,
 'said': 21,
 'with': 22,
 'told': 23,
 'too': 24,
 'many': 25,
 'its': 26,
 'robot': 27,
 'code': 28,
 'jokes': 29,
 'go': 30,
 'for': 31,
 'and': 32,
 'needed': 33,
 'tell': 34,
 'had': 35,
 'just': 36,
 'do': 37,
 'up': 38,
 'only': 39,
 'laugh': 40,
 'programmers': 41,
 'bugs': 42,
 'me': 43,
 'no': 44,
 'his': 45,
 'humor': 46,
 'in': 47,
 'have': 48,
 'good': 49,
 'there': 50,
 'loved': 51,
 'more': 52,
 'relax': 53,
 'is': 54,
 'at': 55,
 'developer': 56,
 'an': 57,
 'sleep': 58,
 'kept': 59,
 'get': 60,
 'connection': 61,
 'on': 62,
 'data': 63,
 'break': 64,
 'were': 65,
 'improve': 66,
 'internet': 67,
 'become': 68,
 'bug': 69,
 'thinks': 70,
 'every': 71,
 'debugging': 72,
 'that': 73,
 'like': 74,
 'itself': 75,
 'dataset': 76,
 'm

In [8]:
tokenizer.word_docs

defaultdict(int,
            {'computer': 36,
             'because': 45,
             'go': 6,
             'to': 35,
             'virus': 1,
             'did': 44,
             'doctor': 1,
             'it': 50,
             'a': 21,
             'had': 5,
             'why': 51,
             'the': 58,
             'i': 31,
             'joke': 8,
             'not': 8,
             'my': 39,
             'but': 30,
             'laugh': 4,
             'laptop': 8,
             'crashed': 1,
             'just': 5,
             'told': 7,
             'dark': 1,
             'attracts': 1,
             'do': 4,
             'light': 1,
             'mode': 2,
             'bugs': 4,
             'prefer': 1,
             'programmers': 4,
             'chess': 1,
             'kickboxing': 1,
             'was': 14,
             'me': 3,
             'beat': 1,
             'for': 6,
             'at': 2,
             'no': 4,
             'match': 1,
             'he': 10,
    

In [9]:
tokenized_sentence=tokenizer.texts_to_sequences(doc)

In [10]:
tokenized_sentence

[[3, 4, 1, 8, 30, 7, 1, 127, 5, 2, 35, 11, 128],
 [9, 23, 6, 18, 11, 19, 10, 2, 4, 20, 40, 2, 36, 129],
 [3, 37, 41, 130, 131, 77, 5, 132, 133, 42],
 [6, 8, 134, 43, 55, 135, 10, 2, 12, 44, 136, 31, 43, 55, 137],
 [3, 4, 1, 56, 30, 138, 5, 15, 139, 38, 78, 45, 79],
 [9, 14, 1, 8, 31, 11, 19, 32, 2, 21, 80, 46, 20, 140],
 [3, 12, 1, 81, 141, 142, 5, 2, 35, 24, 25, 143],
 [9, 17, 7, 144, 145, 146, 10, 9, 147],
 [3, 4, 1, 148, 149, 57, 150, 5, 15, 12, 151, 47, 45, 152],
 [9, 23, 6, 153, 7, 58, 10, 2, 59, 154, 38, 22, 155],
 [3, 4, 1, 16, 82, 1, 83, 7, 156, 1, 157, 158],
 [9, 14, 6, 159, 31, 84, 10, 2, 21, 160, 161, 162, 7, 163],
 [3, 4, 1, 8, 60, 164, 5, 2, 165, 26, 166, 85],
 [6, 167, 32, 9, 48, 11, 168, 61, 10, 86, 2, 169, 170],
 [3, 37, 87, 171, 172, 88, 5, 89, 37, 20, 90, 173],
 [3, 4, 1, 27, 30, 62, 174, 5, 2, 33, 7, 175],
 [9, 14, 6, 8, 7, 176, 10, 2, 39, 91, 92, 177],
 [3, 4, 1, 13, 178, 45, 179, 5, 15, 4, 20, 60, 180],
 [9, 23, 6, 8, 11, 181, 10, 2, 182, 1, 63],
 [3, 4, 1, 93, 64,

In [11]:
input_sequences = []
for seq in tokenized_sentence:
    for i in range(1, len(seq)):
        input_sequences.append(seq[:i+1])

In [12]:
input_sequences

[[3, 4],
 [3, 4, 1],
 [3, 4, 1, 8],
 [3, 4, 1, 8, 30],
 [3, 4, 1, 8, 30, 7],
 [3, 4, 1, 8, 30, 7, 1],
 [3, 4, 1, 8, 30, 7, 1, 127],
 [3, 4, 1, 8, 30, 7, 1, 127, 5],
 [3, 4, 1, 8, 30, 7, 1, 127, 5, 2],
 [3, 4, 1, 8, 30, 7, 1, 127, 5, 2, 35],
 [3, 4, 1, 8, 30, 7, 1, 127, 5, 2, 35, 11],
 [3, 4, 1, 8, 30, 7, 1, 127, 5, 2, 35, 11, 128],
 [9, 23],
 [9, 23, 6],
 [9, 23, 6, 18],
 [9, 23, 6, 18, 11],
 [9, 23, 6, 18, 11, 19],
 [9, 23, 6, 18, 11, 19, 10],
 [9, 23, 6, 18, 11, 19, 10, 2],
 [9, 23, 6, 18, 11, 19, 10, 2, 4],
 [9, 23, 6, 18, 11, 19, 10, 2, 4, 20],
 [9, 23, 6, 18, 11, 19, 10, 2, 4, 20, 40],
 [9, 23, 6, 18, 11, 19, 10, 2, 4, 20, 40, 2],
 [9, 23, 6, 18, 11, 19, 10, 2, 4, 20, 40, 2, 36],
 [9, 23, 6, 18, 11, 19, 10, 2, 4, 20, 40, 2, 36, 129],
 [3, 37],
 [3, 37, 41],
 [3, 37, 41, 130],
 [3, 37, 41, 130, 131],
 [3, 37, 41, 130, 131, 77],
 [3, 37, 41, 130, 131, 77, 5],
 [3, 37, 41, 130, 131, 77, 5, 132],
 [3, 37, 41, 130, 131, 77, 5, 132, 133],
 [3, 37, 41, 130, 131, 77, 5, 132, 133, 42],
 [6

In [13]:
max_len=max([len(x) for x in input_sequences])

In [14]:
max_len

17

In [15]:
from tensorflow.keras.preprocessing.sequence import pad_sequences 
paded_input=pad_sequences(input_sequences,maxlen=max_len,padding='pre' )

In [16]:
 paded_input

array([[  0,   0,   0, ...,   0,   3,   4],
       [  0,   0,   0, ...,   3,   4,   1],
       [  0,   0,   0, ...,   4,   1,   8],
       ...,
       [  0,   0,   0, ...,   2, 376,  95],
       [  0,   0,   0, ..., 376,  95,   1],
       [  0,   0,   0, ...,  95,   1,  76]], shape=(1064, 17), dtype=int32)

In [17]:
x=paded_input[:,:-1]
y=paded_input[:,-1 ]

In [18]:
x

array([[  0,   0,   0, ...,   0,   0,   3],
       [  0,   0,   0, ...,   0,   3,   4],
       [  0,   0,   0, ...,   3,   4,   1],
       ...,
       [  0,   0,   0, ...,   5,   2, 376],
       [  0,   0,   0, ...,   2, 376,  95],
       [  0,   0,   0, ..., 376,  95,   1]], shape=(1064, 16), dtype=int32)

In [19]:
y

array([ 4,  1,  8, ..., 95,  1, 76], shape=(1064,), dtype=int32)

In [20]:
 x.shape

(1064, 16)

In [21]:
y.shape

(1064,)

In [22]:
from keras.utils import to_categorical 
y=to_categorical(y,num_classes=377)

In [23]:
len(tokenizer.word_index  )

376

In [24]:
y.shape

(1064, 377)

In [25]:
 y

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 1., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 1., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]], shape=(1064, 377))

In [26]:
from tensorflow.keras.models import Sequential 
from keras.layers import Embedding,Dense,LSTM 

In [27]:
 model=Sequential()
model.add(Embedding(input_dim=377, output_dim=100, input_shape=(17,)))
model.add(LSTM(200))
model.add(Dense(377,activation='softmax'))
model.compile(loss='categorical_crossentropy',optimizer='adam',metrics=['accuracy'])
model.summary()

D:\New folder\envs\tf\lib\site-packages\keras\src\layers\core\embedding.py:100: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)


Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━┓
┃ Layer (type)                         ┃ Output Shape                ┃         Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━┩
│ embedding (Embedding)                │ (None, 17, 100)             │          37,700 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ lstm (LSTM)                          │ (None, 200)                 │         240,800 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense (Dense)                        │ (None, 377)                 │          75,777 │
└──────────────────────────────────────┴─────────────────────────────┴─────────────────┘

 Total params: 354,277 (1.35 MB)

 Trainable params: 354,277 (1.35 MB)

 Non-trainable params: 0 (0.00 B)

In [28]:
 model.fit(x,y,epochs=100)

Epoch 1/100
34/34 ━━━━━━━━━━━━━━━━━━━━ 6s 45ms/step - accuracy: 0.0705 - loss: 5.4712    
Epoch 2/100
34/34 ━━━━━━━━━━━━━━━━━━━━ 2s 47ms/step - accuracy: 0.0846 - loss: 5.0411 
Epoch 3/100
34/34 ━━━━━━━━━━━━━━━━━━━━ 2s 46ms/step - accuracy: 0.1391 - loss: 4.8142 
Epoch 4/100
34/34 ━━━━━━━━━━━━━━━━━━━━ 3s 49ms/step - accuracy: 0.1711 - loss: 4.5764
Epoch 5/100
34/34 ━━━━━━━━━━━━━━━━━━━━ 2s 46ms/step - accuracy: 0.2030 - loss: 4.3339  
Epoch 6/100
34/34 ━━━━━━━━━━━━━━━━━━━━ 2s 48ms/step - accuracy: 0.2284 - loss: 4.0806 
Epoch 7/100
34/34 ━━━━━━━━━━━━━━━━━━━━ 2s 50ms/step - accuracy: 0.2697 - loss: 3.8383 
Epoch 8/100
34/34 ━━━━━━━━━━━━━━━━━━━━ 2s 46ms/step - accuracy: 0.2998 - loss: 3.5998 
Epoch 9/100
34/34 ━━━━━━━━━━━━━━━━━━━━ 3s 46ms/step - accuracy: 0.3092 - loss: 3.3806
Epoch 10/100
34/34 ━━━━━━━━━━━━━━━━━━━━ 3s 52ms/step - accuracy: 0.3365 - loss: 3.1706
Epoch 11/100
34/34 ━━━━━━━━━━━━━━━━━━━━ 2s 47ms/step - accuracy: 0.3402 - loss: 2.9817 
Epoch 12/100
34/34 ━━━━━━━━━━━━━━━━━━━━ 

In [44]:
text="I tried to debug my "
for i in range(10):
    #tokenize
    token_text=tokenizer.texts_to_sequences([text])[0]
    #padding 
    paded_token_text=pad_sequences([token_text],maxlen=17,padding='pre')
    #Model
    model.predict(paded_token_text)
    #prediction
    pos=np.argmax(model.predict(paded_token_text))
    for word,index in tokenizer.word_index.items():
        if index==pos:
            text=text+" "+word
            print(text)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 117ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 93ms/step
I tried to debug my  life
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 90ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 86ms/step
I tried to debug my  life but
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 109ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 108ms/step
I tried to debug my  life but there
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 118ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 98ms/step
I tried to debug my  life but there were
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 91ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 105ms/step
I tried to debug my  life but there were too
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 95ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 90ms/step
I tried to debug my  life but there were too many
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 91ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 90ms/step
I tried to debug my  life but there were too many errors
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 90ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 82ms/step
I tried to debug my  life but there were too many errors errors
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 86ms/step
